// ============ Single source of truth for all project cards ============
// Used by both the homepage "featured" strip and the full /projects page.
// Array order = homepage featured order (for the featured:true items) and
// the /projects page order (for everything).
export const PROJECTS = [
  {
    id: "arbitrator",
    title: "Arbitrator",
    category: "Desktop App",
    description: "A local working for judge for Labs built with JAVA, JavaFX and Spring Boot.",
    image: null, // screenshot to be added later
    tags: ["Java", "JavaFX", "Spring Boot", "HTML", "CSS", "JavaScript"],
    link: null, // no link yet — card shows "Coming soon"
    featured: true,
  },
  {
    id: "partyjam",
    title: "PartyJam Game",
    category: "Game",
    description: "A chaotic local multiplayer party game made in Unity.",
    image: "assets/projects/PartyJam.png",
    tags: ["Unity", "C#", "Illustrator", "Blender"],
    link: "https://mahir-labib.itch.io/partyjam",
    featured: true,
  },
  {
    id: "automech",
    title: "Automech Website",
    category: "Web App",
    description: "Marketing site for Automech, built from scratch with vanilla web tech.",
    image: "assets/projects/Automech.png",
    tags: ["HTML", "CSS", "JavaScript"],
    link: "https://automech2026.vercel.app",
    featured: true,
  },
  {
    id: "chase",
    title: "CHASE",
    category: "Game",
    description: "A fast-paced top-down chase game built with C++ and raylib.",
    image: "assets/projects/Chase.png",
    tags: ["C++", "raylib", "Illustrator"],
    link: "https://mahir-labib.itch.io/chase",
    featured: true,
  },
  {
    id: "formula-iut",
    title: "Formula IUT Website",
    category: "Web App",
    description: "The official site for IUT's Formula Student racing team.",
    image: "assets/projects/FIUT_website.png",
    tags: ["Python", "HTML", "CSS", "JavaScript"],
    link: "https://formula-iut.vercel.app/",
    featured: true,
  },
  {
    id: "simracing-buttonbox",
    title: "SimRacing Button Box with Display",
    category: "Hardware",
    description: "A custom Arduino button box with a live telemetry display.",
    image: "assets/projects/circuit_diagram.png",
    tags: ["Arduino", "SimHub", "Microcontroller"],
    link: "https://github.com/istamimnaser/SimRacing-Button-Box-With-Display",
    featured: true,
  },
  {
    id: "pockettracker",
    title: "PocketTracker",
    category: "Desktop App",
    description: "A lightweight desktop music player with a custom Qt interface.",
    image: "assets/projects/PocketTracker.png",
    tags: ["C++", "File Handling", "SFML", "Qt (GUI)"],
    link: "https://github.com/ZIZITSU/Pocket-Tracker-Music-Player",
    featured: false,
  },
  {
    id: "flapsnap",
    title: "FlapSnap",
    category: "Game",
    description: "A Flappy-Bird-style arcade game with a hand-drawn look.",
    image: "assets/projects/FlapSnap.png",
    tags: ["Unity", "C#", "Illustrator"],
    link: "https://mahir-labib.itch.io/flapsnap",
    featured: false,
  },
  {
    id: "acc-assistant",
    title: "Assetto Corsa Competizione Assistant",
    category: "Web App",
    description: "A setup guide & assistant for Assetto Corsa Competizione.",
    image: "assets/projects/ACC.png",
    tags: ["HTML5", "CSS3", "JavaScript"],
    link: "https://github.com/ZIZITSU/ACC-Setup-Guide",
    featured: false,
  },
];
